services:
  postgres:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 5s
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "fremfraribe6760"
      POSTGRES_DB: "bookstore"
      POSTGRES_USER: "colacarsten"
      
  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/root/redis
    environment:
      REDIS_PASSWORD: "my-redis-password"
      REDIS_PORT: 6379
      REDIS_DATABASES: 16

  mongo:
    image: mongo:latest
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 5s
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongomorten
      MONGO_INITDB_ROOT_PASSWORD: mongomango
      
  mongo-express:
    image: mongo-express:latest
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongomorten
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongomango
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: "mongo"
      ME_CONFIG_BASICAUTH: false
            
  bookstore-api:
    depends_on:
      mongo:
        condition: service_healthy
      postgres:
        condition: service_healthy
    build:
      context: . 
      dockerfile: AmazonKiller2000/Dockerfile
    ports:
      - "8080:8080"
    restart: always
    environment:
      redis-host: "redis"
      redis-password: "my-redis-password"
      mongodb-url: "mongodb://mongomorten:mongomango@mongo:27017"
      mongodb-name: "bookstore"
      PostgresConnectionString: "Host=postgres;Port=5432;Password=fremfraribe6760;Persist Security Info=True;Username=colacarsten;Database=bookstore"
      
volumes:
  postgres:
  redis: